services:
  nginx:
    image: nginx:alpine
    ports:
      - "9999:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "32M"

  api-1:
    build: .
    image: diemorei/rinhabackend2026:latest  
    expose:
      - "3000"
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "159M"
    environment:
      NODE_OPTIONS: "--max-old-space-size=140"

  api-2:
    build: .
    image: diemorei/rinhabackend2026:latest
    expose:
      - "3000"
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "159M"
    environment:
      NODE_OPTIONS: "--max-old-space-size=140"